import re

confidentialLogs = ""  # initialize variable to hold confidential logs

# open log file and store each confidential log in the confidentialLogs variable
fi = open("mock_log_file.txt", "r")
for line in fi:
    if "confidential" in line:
        confidentialLogs += line
fi.close()

# put the confidential logs into a new log file
fi = open("confidential_logs.txt", "w")
fi.write(confidentialLogs)
fi.close()

susLogsNum = 0  # keep track of how many suspicious logs there are

#  dictionary to keep track of how many suspicious logs were created by each user
userDict = {"user1": 0,
            "user2": 0,
            "user3": 0,
            "user4": 0}

# open the confidential logs file
fi = open("confidential_logs.txt", "r")
for line in fi:  # loop through each line in the file
    date = int(re.sub(":", "", line[11:20]))  # store the timestamp as a number
    if date < 90000 or date > 180000:  # check if log entry was at a suspicious time
        susLogsNum += 1  # Increment total number of sus logs
        userDict[line[22:27]] += 1  # Increment amount of sus logs generated by this user
        print(line)  # print the log
fi.close()

# print the results
print("Total suspicious activities: " + str(susLogsNum))
print("The user with the most suspicious activity is " + max(userDict, key=userDict.get))